### ISSUE TITLE
Update GraphQL for new schemas from database

### ISSUE THREAD

**Issue by alessandro-pianetta** [codeforsanjose/open-disclosure#117]
GraphQL queries will need to be updated to match the new schema of the DB data.

Once @geleazar1000111 merges in her updates for the Election schema, we will be able to go ahead with this fix; @geleazar1000111 please comment here when you get the changes in and merged.

**Comment by ejanzer** [comment]
It looks like the candidate schema is already there. Does it make sense for me to start updating the schema for that now?

**Comment by ejanzer** [comment]
I went ahead and did that here: https://github.com/codeforsanjose/open-disclosure/pull/120

Turns out the schema didn't change much, just flattened it a bit so that Committees is directly accessible on the candidate node now.
