### ISSUE TITLE
Create prototype visualizations comparing contributions across candidates over time

### ISSUE THREAD

**Issue by SmellsLikeCake** [codeforsanjose/open-disclosure#14]
Using the district9.csv dataset found here: https://drive.google.com/drive/folders/1RwaLU3564B60yMjCZKl2PCRK5-gKysDn create one or more visualizations which compare how the contributions received by the different candidates standing for council member in district 9 changed over time. Note that only transactions with Form_Type = A are contributions. See the 460 codebook for more details: https://docs.google.com/document/d/1N_NCdYoBODUJwagAGNPKiQUGdHje11jjgZoQuxZY8I0/edit

**Comment by gardenFiend138** [comment]
Can this issue be closed now?
