### ISSUE TITLE
Data pipelining

### ISSUE THREAD

**Issue by SmellsLikeCake** [codeforsanjose/open-disclosure#17]
Establish a data pipeline for taking data off the website, cleaning it and combining it into a single structure. There is a scraper in the github already, and a de-deduplicating script in the google drive: https://drive.google.com/drive/folders/1RwaLU3564B60yMjCZKl2PCRK5-gKysDn

**Comment by laurenrenaud** [comment]
Data pipeline can also include features engineering.

Would be helpful to include what seat someone is running for in a standardized format.

**Comment by rkiddy** [comment]
Did this suggestion lead to the development of the current scraper? Was that done independently of this suggestion? What is the relevance of this suggestion now?

**Comment by laurenrenaud** [comment]
Fwiw I have not been around to take action on this, don't know of others have.

**Comment by rkiddy** [comment]
@darpham This issue could be closed, since it seems to not be relevant to the current work on the scraper and other data work, no?

**Comment by rwalek668** [comment]
This ticket is complete/too large to be useful.
