### ISSUE TITLE
San José live election section needs updates 

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/open-disclosure#184]
- [x] San José live election snapshot - update the source so it's the latest data, not just July 19, 2020.  
- [x] Update the placeholder "XXX" so it reflects the total donations from the city of San José
- [x] Consider changing the language to "donations from the city of San José to  donations from San José residents". Otherwise, it sounds like the government of San José is donating money to candidates. 
- [x] "4 candidates running"--> should be changed to "4 candidates running in 2 city council races". Otherwise it's misleading. There are many school board, and other open elections in San José.

![Screen Shot 2020-10-18 at 10 29 02 AM](https://user-images.githubusercontent.com/20962963/96375275-d1249180-112c-11eb-9ae0-2463d4e7f90d.png)

**Comment by ejanzer** [comment]
1: That's the date we get from the API, so I guess we need to update that there, cc @geleazar1000111 
2: Fixed in #191 
3: I'm not sure if that text will fit in that space, maybe we can say "Of donations from residents of San José"? 
4: I can do "X candidates running in Y races", but I don't think we want to put "city council" in there because if we add more races they'll automatically be included here. Does that sound good?

**Comment by ychoy** [comment]
> 2: Fixed in #191

Thanks for fixing this, Emily! However, I don't see it deployed to production https://open-disclosure.codeforsanjose.com/

**Comment by ychoy** [comment]
> I'm not sure if that text will fit in that space, maybe we can say "Of donations from residents of San José"?

Yes, or even just "Of donations from San José residents"

**Comment by ychoy** [comment]
> I can do "X candidates running in Y races", but I don't think we want to put "city council" in there because if we add more races they'll automatically be included here. Does that sound good?

Yes, that sounds good! Thanks!

**Comment by ejanzer** [comment]
> Thanks for fixing this, Emily! However, I don't see it deployed to production https://open-disclosure.codeforsanjose.com/

Yup, the fix is merged but not deployed yet.

**Comment by alessandro-pianetta** [comment]
Made one minor change in #208 but is otherwise complete
