### ISSUE TITLE
Footer Update

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/open-disclosure#186]
Some of this footer language was copied from Open Oakland's website. We should update the language so it more closely reflects our sources. This project, to my understanding, isn't made in partnership with the City Clerk's office, so I recommend changing the language.

- [x] Update this line:

BEFORE:
Brought to you by Open San José and San José's Public Ethics Commission

AFTER:
Made by Code for San José 

- [x] Update this line:
BEFORE: Campaign finance data provided by the City of San José Public Ethics Commission Public Portal for Campaign Finance and Lobbyist Disclosure. Candidate and ballot measure information gathered from information provided to the Santa Clara County Registrar of Voters by the City of San José.

AFTER:
 Campaign finance data provided by the City of San José's[ Public Access Portal (CampaignDocs eRetrieval)](https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/). Candidate and ballot measure information gathered from information provided to the [Santa Clara County Registrar of Voters](https://www.sccgov.org/sites/rov/Pages/Registrar-of-Voters.aspx).

- [x] Add Code for San José logo

**Comment by ejanzer** [comment]
It looks like @alessandro-pianetta already updated the footer in #174 to just say "Brought to you by Code for San José". @ychoy is that ok, or do you want us to add in what you suggested?

**Comment by ychoy** [comment]
Can we add Code for San José's logo to the footer? 

I think it would be helpful to indicate the source, unless that is already covered by About/FAQ sections.

By the way, this is the text I'm seeing on the footer of https://open-disclosure.codeforsanjose.com/. I think the frontend deployment is not in sync with what's on master branch.

```
Special thanks to Open Oakland's Open Disclosure for the inspiration.
Brought to you by Open San José and San José's Public Ethics Commission

Campaign finance data provided by the City of San José Public Ethics Commission Public Portal for Campaign Finance and Lobbyist Disclosure. Candidate and ballot measure information gathered from information provided to the Santa Clara County Registrar of Voters by the City of San José.
```

**Comment by ejanzer** [comment]
@ychoy Yup, the deployed version isn't up-to-date. This is what I currently see: 
<img width="741" alt="Screen Shot 2020-10-20 at 10 16 23 PM" src="https://user-images.githubusercontent.com/2308395/96676320-e878a000-1321-11eb-9adc-6e97e9aaf7e6.png">

**Comment by alessandro-pianetta** [comment]
Moved the special thanks to Open Oakland to the About Page, updated the text there, and added the logo to the footer. #208
