### ISSUE TITLE
Update README and homepage with info about UI from OpenDislcosure.io

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/open-disclosure#24]
Since the UI based on Open Oakland's  Open Disclosure project https://www.opendisclosure.io/, we should reference it in our README and on the footer of the homepage (or on the "Open Source page?") and give credit and thanks to them.

@SmellsLikeCake

**Comment by alessandro-pianetta** [comment]
I let Diane know about this!

**Comment by gardenFiend138** [comment]
Seems like this issue has been addressed, is it safe to close?

**Comment by gardenFiend138** [comment]
Seems like this issue has been addressed, is it safe to close?

**Comment by alessandro-pianetta** [comment]
It doesn't look like it got included; I'll ping the designers to add it in somewhere!
