### ISSUE TITLE
Confirm user stories for MVP (Version 1)

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/open-disclosure#3]
These are draft user stories for MVP (version 1) to complete by Dec 31, 2019. 

1. A user can see a list of election categories:
2. President of the United States
3. United States Representative in Congress
4. California State Senator and Member of the State Assembly
5. The user can select one category
6. The use can select one candidate
7. The user will see a list of donors, from highest donation to lowest donation. Include information about the donor like their job and donation amount.
8. The user can see a list of where the donors are from: San Jose, Santa Clara County, California, Other States

Helen @SmellsLikeCake, I'd love to get your feedback on these draft user stories for MVP. 

Once we get these confirmed, we can create separate GitHub issues for each of the stories.

**Comment by SmellsLikeCake** [comment]
To summarize what I wrote on Slack, I think we need to focus on local elections (i.e. City of San Jose level) before we move onto county, state and country levels, as each of these levels have different data sources and requirements. I also think we need to focus on candidates' official campaign committees first, as Open Oakland did, before broadening our scope to cover other committees and other areas.

Therefore my suggested draft user stories are:
1. A user can see a list of local election categories:
- Mayoral candidates of City of San Jose
- Council member candidates of City of San Jose
2. The user can select one category
3. The user can select one candidate
4. The user will see a list of donors, from highest donation to lowest donation. Include information about the donor like their donation amount, zip code. Also include information about expenditures, broken down into categories, recipients and amounts.
5. The user can see a list of where the donors are from: San Jose, Santa Clara County, California, Other States

My intention is to open issues asking people to do things like "Make a visualization showing donations to Mayoral candidate X split by zip code".

I will update the ReadMe accordingly.
