### ISSUE TITLE
Create Flask API for Data Pipeline

### ISSUE THREAD

**Issue by darpham** [codeforsanjose/open-disclosure#48]
New sub-folder 'data_api' for created under 'data_pipeline'

This API will:
- Scrape the data on either a certain cadence or small sub-check (new forms to download)
- Complete the data processing/aggregation then load the data into a MySQL database

Additionally serves requests for certain election data: (this will require new tables to be uploaded into MySQL)
- General election info (total $ amount, etc.)
- Candidate Info (Candidate name, total contributions, etc.)

**Comment by rwalek668** [comment]
https://github.com/codeforsanjose/open-disclosure/issues/47 will define the shape of the API.

**Comment by geleazar1000111** [comment]
Taking ownership of this one
Initial progress located in https://github.com/geleazar1000111/cfsj-data-apis

**Comment by rwalek668** [comment]
Based on discussions during our sync meeting, one initial step here towards the creation of the full API is to create a version which returns fake data so the frontend can try to connect to it.  Something along the lines of GetTotalContributions which just returns a number (i.e. 10000000).

**Comment by geleazar1000111** [comment]
AC #1: Create scraper endpoint to initialize the scraper constructor from localhost
AC #2: Return fake data from an API endpoint (i.e. return 100000 from /total-contributions)
AC #3: Return candidate info via POST request (i.e. total amount candidate rose)

**Comment by darpham** [comment]
@geleazar1000111 if you feel like the requirements of this issue are fulfilled, feel free to close it out :)
