### ISSUE TITLE
Create prototype visualizations of contributions over time

### ISSUE THREAD

**Issue by SmellsLikeCake** [codeforsanjose/open-disclosure#5]
Using the liccardo_2018.csv dataset saved here: https://drive.google.com/drive/folders/1RwaLU3564B60yMjCZKl2PCRK5-gKysDn create one or more visualizations that show the contributions received by Sam Liccardo's campaign over time. Note that only the transactions with Form_Type = A are contributions. See the 460 Codebook (https://docs.google.com/document/d/1N_NCdYoBODUJwagAGNPKiQUGdHje11jjgZoQuxZY8I0/edit) for further details.

**Comment by abhishekmangla** [comment]
I made contributions/day over time and published on Flourish: https://public.flourish.studio/visualisation/1065073/

I also made cumulative contributions over the whole campaign:
https://public.flourish.studio/visualisation/1065513/
