### ISSUE TITLE
install and run of scraper gives an error

### ISSUE THREAD

**Issue by rkiddy** [codeforsanjose/open-disclosure#64]
I have been setting up tests for things I do using aws boxes and auto-load scripts. It looks as though this is needed here. I will get on it.

cheers - ray

Just FYI:

     % git clone https://github.com/codeforsanjose/open-disclosure.git
     Cloning into 'open-disclosure'...
     remote: Enumerating objects: 506, done.
     remote: Counting objects: 100% (506/506), done.
     remote: Compressing objects: 100% (325/325), done.
     remote: Total 937 (delta 258), reused 385 (delta 167), pack-reused 431
     Receiving objects: 100% (937/937), 11.66 MiB | 3.30 MiB/s, done.
     Resolving deltas: 100% (441/441), done.
     %
     % cd open-disclosure
     %
     % cd data_pipeline/scraper
     ray@rrk scraper % virtualenv env
     created virtual environment CPython3.7.3.final.0-64 in 428ms
       creator CPython3macOsFramework(dest=/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env, clear=False, global=False)
       seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/ray/Library/Application Support/virtualenv/seed-app-data/v1.0.1)
       activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
     %
     % source env/bin/activate
     (env) %
     (env) % python3 -m pip install chromedriver_binary webdriver-manager selenium
     Collecting chromedriver_binary
       Downloading chromedriver-binary-85.0.4183.38.0.tar.gz (3.6 kB)
     Collecting webdriver-manager
       Downloading webdriver_manager-3.2.1-py2.py3-none-any.whl (16 kB)
     Collecting selenium
       Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     Collecting crayons
       Downloading crayons-0.3.1-py2.py3-none-any.whl (4.6 kB)
     Collecting configparser
       Using cached configparser-5.0.0-py3-none-any.whl (22 kB)
     Collecting requests
       Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
     Collecting urllib3
       Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     Collecting colorama
       Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
     Collecting certifi>=2017.4.17
       Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     Collecting chardet<4,>=3.0.2
       Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     Collecting idna<3,>=2.5
       Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
     Building wheels for collected packages: chromedriver-binary
       Building wheel for chromedriver-binary (setup.py) ... done
       Created wheel for chromedriver-binary: filename=chromedriver_binary-85.0.4183.38.0-py3-none-any.whl size=7702049 sha256=1b33b906747b5da1f6ff8af7eb734757b93eb4361672e6face9620248b857d19
       Stored in directory: /Users/ray/Library/Caches/pip/wheels/ed/9c/7c/81565815d07eb410cf5e63f896b5cbbcb012c690f1952cf00e
     Successfully built chromedriver-binary
     Installing collected packages: chromedriver-binary, colorama, crayons, configparser, certifi, urllib3, chardet, idna, requests, webdriver-manager, selenium
     Successfully installed certifi-2020.6.20 chardet-3.0.4 chromedriver-binary-85.0.4183.38.0 colorama-0.4.3 configparser-5.0.0 crayons-0.3.1 idna-2.10 requests-2.24.0 selenium-3.141.0 urllib3-1.25.10 webdriver-manager-3.2.1
     WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
     You should consider upgrading via the '/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env/bin/python3 -m pip install --upgrade pip' command.
     % 
     (env) % 
     (env) % python ./scraper.py
     
       File "./scraper.py", line 258
         self.driver, search_page_num, self.BALLOT_TYPE
            ^
     SyntaxError: invalid syntax

**Comment by rwalek668** [comment]
I've updated the documentation, and some additional fixes to the script were put in by Darren.  If you are still running into any troubles, please let us know. THanks!
