### ISSUE TITLE
Complete the missing columns in the 460 codebook

### ISSUE THREAD

**Issue by SmellsLikeCake** [codeforsanjose/open-disclosure#9]
The 460 Codebook describes the meaning of each column in the 460 Excel documents containing the campaign finance information. It is saved here and needs completing: https://docs.google.com/document/d/1N_NCdYoBODUJwagAGNPKiQUGdHje11jjgZoQuxZY8I0/edit

**Comment by abhishekmangla** [comment]
I didn't have edit access, so I made a copy and completed the table for all columns: 
https://docs.google.com/document/d/1D-gESa9IwMaG4uGEqZwpIVSI8OkZ3MMMSVUEXlUeHuk/edit?usp=sharing

I heavily relied on using https://netfile.com/Filer/Content/docs/cal_format_201.pdf as a reference.
